site_name: Interrogation Room Ai
site_description: |
  🕵️ A game where you need to solve police cases by interrogating characters controlled by ai
repo_url: https://github.com/ZamboniMarco99/interrogation-room-ai
repo_name: ZamboniMarco99/interrogation-room-ai
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
  - autorefs
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme:deepblue
  features:
    - search.suggest
    - search.highlight
    - navigation.expand
    - navigation.top
    - toc.follow
    - toc.integrate
markdown_extensions:
  - admonition # enables callouts
  - attr_list # add HTML to  markdown inlines/blocks
  - pymdownx.details # enables collapsible callouts
  - pymdownx.superfences # arbitrary nesting of code and content blocks
  - pymdownx.highlight # highlight code
  - pymdownx.inlinehilite # highlight code
  - pymdownx.tabbed: # tab panes (e.g. different macos/win snippet)
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: "#"
nav:
  - Home: index.md
  - Examples: examples.md
  - API Reference: reference.md
extra:
  version:
    provider: mike
    default: latest
